language: csharp
dotnet: 6.0.300
dist: xenial
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - libunwind8-dev

before_install:
  - nvm install 18
  - dotnet tool restore

script:
  - dotnet run --project ./build/Build.fsproj -- build
